apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-staging
spec:
  selector:
    matchLabels:
      app: demo-api-staging
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: demo-api-staging
    spec:
      containers:
        - name: demo-api-staging
          image: gcr.io/alexislagante/demo-api:1.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "40m"
            requests:
              cpu: "40m"
          env:
            - name: APP_ENV
              value: staging
          ports:
            - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: demo-api-service-staging
spec:
  selector:
    app: demo-api-staging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000