apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-dev
spec:
  selector:
    matchLabels:
      app: demo-api-dev
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: demo-api-dev
    spec:
      containers:
        - name: demo-api-dev
          image: gcr.io/alexislagante/demo-api:v2
          resources:
            limits:
              cpu: "25m"
            requests:
              cpu: "25m"
          env:
            - name: APP_ENV
              value: dev
          ports:
            - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: demo-api-service-dev
spec:
  selector:
    app: demo-api-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000