apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-prod
spec:
  selector:
    matchLabels:
      app: demo-api-prod
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: demo-api-prod
    spec:
      containers:
        - name: demo-api-prod
          image: gcr.io/alexislagante/demo-api:1.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "50m"
            requests:
              cpu: "50m"
          env:
            - name: APP_ENV
              value: prod
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 10
---

apiVersion: v1
kind: Service
metadata:
  name: demo-api-service-prod
spec:
  selector:
    app: demo-api-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000