apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-prod
spec:
  selector:
    matchLabels:
      app: demo-api-prod
  replicas: 5
  template:
    metadata:
      labels:
        app: demo-api-prod
    spec:
      containers:
        - name: demo-api-prod
          image: gcr.io/alexislagante/demo-api:v1
          resources:
            limits:
              cpu: "50m"
            requests:
              cpu: "50m"
          env:
            - name: APP_ENV
              value: prod
          ports:
            - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: demo-api-service-prod
spec:
  selector:
    app: demo-api-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000